import fs from "node:fs"
import path from "node:path"
import { __root, ROOT_ENV_PATH } from "./path.js"
import { appEnvOutputs, confTemplateOutputs, SECRETS_PATH } from "../init-env.js"
import { certDirectories } from "./cert-utils.js"
import { configMatchesTemplate, resetMasterConfig } from "./config-utils.js"
import { opensearchConfigOutputs } from "./opensearch-utils.js"
import { state } from "./state.js"
import { invalidateDependents } from "./steps.js"
import { downContainers } from "./docker-utils.js"
import { deleteApp } from "./app-utils.js"

const COMPOSE_FILES = ["docker-compose.yml", "docker-compose.ext.yml"]

/** Same fallback run.js's dispatcher uses: state is the authority once set. */
function currentEnv() {
  return state.current.environment || "dev"
}

/** Paths each clear target owns. Used both to remove them and to decide
 * whether the menu entry has anything to do. */
export function targetPaths(target) {
  switch (target) {
    case "compose": return COMPOSE_FILES.map(f => path.join(__root, f))
    case "env": return [ROOT_ENV_PATH, ...appEnvOutputs()]
    // opensearch.yml is generated by the prod-only osSecurity step rather than
    // by conf_templates, but it is the same kind of artifact and clearing
    // should not leave it behind
    case "templates": return [...confTemplateOutputs(), ...opensearchConfigOutputs()]
    // every directory generateCertificates() writes to, so clearing stays
    // symmetric with generating
    case "certs": return certDirectories()
    case "secrets": return [SECRETS_PATH]
    default: return []
  }
}

/** Which of a target's paths currently exist. */
export function existingPaths(target) {
  return targetPaths(target).filter(p => fs.existsSync(p))
}

/** Removes the paths that exist and returns exactly what was removed. */
function removePaths(target) {
  const removed = []
  for (const p of existingPaths(target)) {
    fs.rmSync(p, { recursive: true, force: true })
    removed.push(p)
  }
  return removed
}

/** "directory" -> "directories", "file" -> "files". */
function plural(noun, count) {
  if (count === 1) return noun
  return noun.endsWith("y") ? `${noun.slice(0, -1)}ies` : `${noun}s`
}

/** Prints what was removed, then summarises for the result banner. */
function report(removed, noun) {
  if (removed.length === 0) return { message: `no ${plural(noun, 0)} to remove`, noop: true }
  for (const p of removed) console.log(`  removed ${p}`)
  return { message: `removed ${removed.length} ${plural(noun, removed.length)}` }
}

export function clearCompose() {
  const removed = removePaths("compose")
  state.setStep("dockerFilesCopied", false)
  state.setDocker("initialized", false)
  invalidateDependents("dockerFilesCopied", currentEnv())
  return report(removed, "compose file")
}

export function clearEnvFiles() {
  const removed = removePaths("env")
  state.setStep("env", false)
  invalidateDependents("env", currentEnv())
  return report(removed, "env file")
}

export function clearTemplates() {
  const removed = removePaths("templates")
  const env = currentEnv()
  // Two independent roots: this target covers both applyConf's outputs
  // (pgadmin, keycloak realm, nginx.conf) and osSecurity's (opensearch.yml).
  state.setStep("applyConf", false)
  state.setStep("osSecurity", false)
  invalidateDependents("applyConf", env)
  invalidateDependents("osSecurity", env)
  return report(removed, "rendered template")
}

export function clearCerts() {
  const removed = removePaths("certs")
  state.setStep("certs", false)
  invalidateDependents("certs", currentEnv())
  return report(removed, "certificate directory")
}

/**
 * Deletes the stored production secrets, so the next prod "env" step mints a
 * fresh set. Irreversible, and only correct alongside clearing the volumes
 * that were initialised with the old ones.
 */
export function clearSecrets() {
  const removed = removePaths("secrets")
  return report(removed, "secrets file")
}

/**
 * Resets master.config.json AND invalidates every step derived from it —
 * resetMasterConfig() itself only touches the file, since config-utils.js
 * stays state-agnostic (it's the config, not the CLI's tracking of it).
 * Without this, every step from "config" onward kept showing "done" against
 * values that no longer existed.
 */
function clearConfig() {
  const result = resetMasterConfig()
  if (!result.noop) {
    state.setStep("config", false)
    invalidateDependents("config", currentEnv())
  }
  return result
}

/**
 * `docker compose down` — stops and removes containers and networks, but
 * leaves volumes intact, so database contents survive.
 */
export async function clearContainers() {
  await downContainers(false)
  state.setDocker("containarized", false)
  return "containers and networks removed (volumes kept)"
}

/**
 * `docker compose down -v` — the above plus every volume. Irreversible: this
 * is what destroys database contents, which is why it is a separate entry
 * rather than a flag on the one above.
 */
export async function clearVolumes() {
  await downContainers(true)
  state.setDocker("containarized", false)
  state.setDocker("initialized", false)
  return "containers, networks and volumes removed"
}

/** Deletes the pm2 processes for both apps. */
export async function clearApps() {
  await deleteApp("frontend")
  await deleteApp("backend")
  return "pm2 processes deleted"
}

export function resetAppSetup() {
  state.setAppSetup("frontend", false)
  state.setAppSetup("backend", false)
  return "frontend and backend marked as not set up"
}

/**
 * Wipes .cli-state.json back to defaults, keeping the selected environment —
 * see StateManager.reset() for why that one field survives.
 */
export function resetState() {
  const environment = state.reset()
  return environment
    ? `CLI state reset to defaults (environment kept: ${environment})`
    : "CLI state reset to defaults"
}

/** One-line summary of which generated artifacts currently exist. */
export function describeArtifacts() {
  const files = ["env", "compose", "templates", "certs", "secrets"]
    .map(t => `${t} ${existingPaths(t).length > 0 ? "✓" : "–"}`)
  // master.config.json always exists (it is recreated on read), so what is
  // worth reporting is whether it still matches the template
  return [...files, `config ${configMatchesTemplate() ? "–" : "edited"}`].join(" · ")
}

/**
 * Whether one CLEAR_TARGETS entry currently has anything to do, and what to
 * show for it. Shared by the interactive Clear menu and the `clear list`
 * dispatcher output, which previously derived this independently — the
 * dispatcher version never accounted for `needsContainers`, so `containers`/
 * `volumes` always showed a blank detail there even when containers existed.
 *
 * @param {object} entry a CLEAR_TARGETS value
 * @param {Array|null} containers getContainerStates() result, or null if it
 *        could not be queried (e.g. the root .env is missing)
 * @returns {{ disabled: boolean, disabledReason: string, hint: string }}
 */
export function describeClearTarget(entry, containers) {
  if (entry.needsContainers) {
    const disabled = containers === null || containers.length === 0
    return {
      disabled,
      disabledReason: containers === null ? "cannot check (.env missing?)" : "no containers exist",
      hint: containers?.length ? `${containers.length} container${containers.length === 1 ? "" : "s"}` : "",
    }
  }

  const matches = entry.matchesTemplate ? entry.matchesTemplate() : null
  if (matches !== null) {
    return {
      disabled: matches,
      disabledReason: "matches template",
      hint: matches ? "matches template" : "differs from template",
    }
  }

  const owned = entry.target ? existingPaths(entry.target) : null
  if (owned !== null) {
    return {
      disabled: owned.length === 0,
      disabledReason: "nothing to remove",
      hint: `${owned.length} file${owned.length === 1 ? "" : "s"}`,
    }
  }

  return { disabled: false, disabledReason: "nothing to remove", hint: "" }
}

/**
 * Everything the dispatcher's `clear <target>` can run.
 *
 * `confirm` is the interactive warning shown for a destructive target; the
 * non-interactive dispatcher requires --yes for the same set.
 *
 * Ordering note: targetPaths("env") and ("templates") resolve their paths
 * through master.config.json, so anything that clears several targets at once
 * must leave `config` until last — resetting it first would change which files
 * the other targets believe they own.
 */
export const CLEAR_TARGETS = {
  containers: { label: "Stop & remove containers (keep volumes)", run: clearContainers, needsContainers: true },
  volumes: {
    label: "Stop & remove containers + volumes",
    run: clearVolumes,
    destructive: true,
    needsContainers: true,
    confirm: "Remove all containers AND volumes? Database contents will be lost.",
  },
  compose: { label: "Remove copied docker-compose files", run: clearCompose, target: "compose" },
  env: { label: "Remove generated env files", run: clearEnvFiles, target: "env" },
  templates: { label: "Remove rendered config templates", run: clearTemplates, target: "templates" },
  certs: { label: "Remove generated certificates", run: clearCerts, target: "certs" },
  apps: { label: "Stop & delete pm2 processes", run: clearApps },
  "app-state": { label: "Reset app setup state", run: resetAppSetup },
  secrets: {
    label: "Delete stored production secrets",
    run: clearSecrets,
    target: "secrets",
    destructive: true,
    confirm: "Delete the stored production secrets? The next prod setup mints new ones, " +
      "which existing database volumes will reject — you would have to clear those too.",
  },
  config: {
    label: "Reset master.config.json to template defaults",
    run: clearConfig,
    destructive: true,
    matchesTemplate: configMatchesTemplate,
    confirm: "Reset master.config.json? Any values you edited by hand will be lost.",
  },
  state: {
    label: "Reset CLI state",
    run: resetState,
    destructive: true,
    confirm: "Reset the CLI state file? All recorded progress will be lost (the environment is kept).",
  },
}
