import fs from 'node:fs';
import path from 'node:path';
import { __docker } from './path.js';
import { execInContainer, requireRunningService } from './docker-utils.js';
import { parseEnvFile, ROOT_ENV_PATH } from './env-utils.js';
import { distinguishedName, OPENSEARCH_ADMIN_CN, OPENSEARCH_NODE_CN, CA_CERT } from './cert-utils.js';
import { consoleLog } from './logger.js';
import { UsageError } from './runner.js';

/**
 * OpenSearch security for production.
 *
 * In dev the security plugin is off (docker-compose.dev.yml sets
 * DISABLE_SECURITY_PLUGIN). In prod it is on, so the cluster speaks HTTPS and
 * rejects anonymous requests, and every consumer needs credentials.
 *
 * This is deliberately split in two, because the two halves can only run at
 * different times:
 *
 *   1. generateNodeConfig() — before the stack starts. Pure text generation;
 *      opensearch.yml is bind-mounted, so it has to exist on disk first or
 *      docker creates a directory in its place.
 *
 *   2. configureSecurity() — after the cluster is up, inside the container
 *      that is already running. Everything here needs the cluster or the
 *      tools that ship with it: bcrypt hashing (there is no bcrypt in Node's
 *      standard library) and securityadmin. It authenticates with the ADMIN
 *      CERTIFICATE rather than a password, so it works on a cluster whose
 *      credentials are still the shipped defaults.
 *
 * That second step is what removes the demo users. The image ships accounts
 * (admin, kibanaro, logstash, readall, snapshotrestore…) whose bcrypt hashes
 * are published in the OpenSearch repository, and `admin` is marked reserved,
 * which means the REST API refuses to change it — only securityadmin can.
 * Between first boot and this step those accounts exist, on a network that is
 * `internal: true` and publishes no port; running it is part of bringing prod
 * up, not an optional extra.
 */

export const OPENSEARCH_CONF_DIR = path.join(__docker, 'opensearch');
export const NODE_CONFIG_PATH = path.join(OPENSEARCH_CONF_DIR, 'opensearch.yml');

/** The application's own OpenSearch user — used by the backend and by pgsync. */
export const APP_USER = 'nbcg_app';
/** Dashboards authenticates to the cluster as this reserved account. */
export const DASHBOARDS_USER = 'kibanaserver';

const APP_ROLE = 'nbcg_app_role';
const SERVICE = 'opensearch-node';

/** Certificate paths as seen from inside the container. */
const IN_CONTAINER = {
  ca: 'config/certs/ca.crt',
  cert: 'config/certs/admin.crt',
  key: 'config/certs/admin.key',
};

/** Demo accounts the image ships. Their hashes are public; they must not survive. */
const DEMO_USERS = ['anomalyadmin', 'kibanaro', 'logstash', 'readall', 'snapshotrestore'];

/** Files this module writes, for the clear target. */
export function opensearchConfigOutputs() {
  return [NODE_CONFIG_PATH];
}

/**
 * "osSecurity" step (prod only). Writes config/opensearch.yml.
 *
 * Paths in it are relative to the container's config directory, which is where
 * the compose file mounts the certificates issued by the `certs` step.
 */
export function generateNodeConfig() {
  if (!fs.existsSync(CA_CERT))
    throw new UsageError(`The certificate authority does not exist yet — run the "certs" step first.`);

  fs.mkdirSync(OPENSEARCH_CONF_DIR, { recursive: true });

  const content = `---
# Generated by the "osSecurity" step — edit master.config.json, not this file.
cluster.name: opensearch-cluster
network.host: 0.0.0.0

# TLS. The keys the certs step issues are PKCS#8; the security plugin accepts
# nothing else, which is why cert-utils.js uses genpkey rather than genrsa.
plugins.security.ssl.transport.pemcert_filepath: certs/node.crt
plugins.security.ssl.transport.pemkey_filepath: certs/node.key
plugins.security.ssl.transport.pemtrustedcas_filepath: certs/ca.crt
# Nodes address each other by compose service name, which the node
# certificate's SAN covers; strict hostname verification adds nothing here.
plugins.security.ssl.transport.enforce_hostname_verification: false

plugins.security.ssl.http.enabled: true
plugins.security.ssl.http.pemcert_filepath: certs/node.crt
plugins.security.ssl.http.pemkey_filepath: certs/node.key
plugins.security.ssl.http.pemtrustedcas_filepath: certs/ca.crt

# Initialise the security index from the image's shipped defaults on first
# start, so the cluster comes up healthy and its dependants can start. Those
# defaults include demo accounts with published passwords — the
# "Configure OpenSearch security" action replaces them, and must be run.
plugins.security.allow_default_init_securityindex: true

# Derived from master.config.json's certificate subject (cert-utils.js), so a
# DN can never disagree with the certificate that was actually issued.
plugins.security.authcz.admin_dn:
  - '${distinguishedName(OPENSEARCH_ADMIN_CN)}'
plugins.security.nodes_dn:
  - '${distinguishedName(OPENSEARCH_NODE_CN)}'

plugins.security.audit.type: internal_opensearch
plugins.security.restapi.roles_enabled: ["all_access", "security_rest_api_access"]
`;

  fs.writeFileSync(NODE_CONFIG_PATH, content, 'utf8');
  consoleLog('INFO', `Wrote ${NODE_CONFIG_PATH}`);
  return { message: 'opensearch.yml written (TLS + admin DN)' };
}

function requireSecret(env, key) {
  const value = env[key];
  if (!value)
    throw new UsageError(`${key} is not in the root .env — run the "env" and "config" steps for prod first.`);
  return value;
}

/** Runs a shell snippet in the running cluster container and returns stdout. */
async function inCluster(script, env = {}) {
  const out = await execInContainer(SERVICE, ['sh', '-c', script], {
    stdio: ['inherit', 'pipe', 'inherit'],
    env,
  });
  return (out || '').trim();
}

/**
 * curl against the local cluster, authenticated by the admin certificate.
 * Password-independent by design: it has to work before the passwords are ours.
 */
function curl(method, apiPath, { bodyFrom } = {}) {
  const data = bodyFrom ? `-H 'Content-Type: application/json' --data-binary "$${bodyFrom}"` : '';
  return `curl -s -o /dev/null -w '%{http_code}' -X ${method} ` +
    `--cacert ${IN_CONTAINER.ca} --cert ${IN_CONTAINER.cert} --key ${IN_CONTAINER.key} ` +
    `${data} "https://localhost:9200${apiPath}"`;
}

/**
 * Docker action: turn a freshly-initialised cluster into the configured one.
 *
 * @returns {Promise<{message: string}>}
 */
export async function configureSecurity() {
  await requireRunningService(SERVICE);

  const rootEnv = fs.existsSync(ROOT_ENV_PATH) ? parseEnvFile(ROOT_ENV_PATH) : {};
  const passwords = {
    PW_ADMIN: requireSecret(rootEnv, 'OPENSEARCH_INITIAL_ADMIN_PASSWORD'),
    PW_APP: requireSecret(rootEnv, 'OPENSEARCH_APP_PASSWORD'),
    PW_DASH: requireSecret(rootEnv, 'OPENSEARCH_DASHBOARDS_PASSWORD'),
  };

  // hash.sh reads the password from the environment rather than argv, so no
  // cleartext reaches the container's process list.
  consoleLog('INFO', 'Hashing credentials with the cluster\'s own hash.sh...');
  const hashOut = await inCluster(
    Object.keys(passwords)
      .map(name => `echo "@@${name}"; plugins/opensearch-security/tools/hash.sh -env ${name} 2>/dev/null | tail -1`)
      .join('; '),
    passwords,
  );

  const hashes = {};
  let current = null;
  for (const line of hashOut.split('\n')) {
    const marker = line.match(/^@@(PW_[A-Z]+)$/);
    if (marker) { current = marker[1]; continue; }
    if (current && line.trim().startsWith('$2')) { hashes[current] = line.trim(); current = null; }
  }
  for (const name of Object.keys(passwords))
    if (!hashes[name]) throw new Error(`hash.sh produced no bcrypt hash for ${name}`);

  // internalusers is replaced wholesale — that is what removes the demo
  // accounts, including the reserved `admin` the REST API refuses to touch.
  const internalUsers = `---
_meta:
  type: "internalusers"
  config_version: 2

admin:
  hash: "${hashes.PW_ADMIN}"
  reserved: true
  backend_roles:
  - "admin"
  description: "Cluster administrator (OPENSEARCH_INITIAL_ADMIN_PASSWORD)"

${DASHBOARDS_USER}:
  hash: "${hashes.PW_DASH}"
  reserved: true
  description: "OpenSearch Dashboards server account (OPENSEARCH_DASHBOARDS_PASSWORD)"

${APP_USER}:
  hash: "${hashes.PW_APP}"
  reserved: false
  opendistro_security_roles:
  - "${APP_ROLE}"
  description: "Backend and pgsync (OPENSEARCH_APP_PASSWORD)"
`;

  // The role and its mapping go through the REST API rather than a file: that
  // way the image's own roles.yml — ~550 lines of built-in roles — is left
  // alone. securityadmin replaces a whole config type, so uploading a partial
  // roles.yml would delete all_access, kibana_user and the rest with it.
  const role = JSON.stringify({
    description: "Read/write on the application's indices, for the backend and pgsync",
    cluster_permissions: ['cluster_monitor', 'cluster_composite_ops', 'indices:data/read/scroll*'],
    index_permissions: [{ index_patterns: ['records*', 'drafts*'], allowed_actions: ['indices_all'] }],
  });
  const mapping = JSON.stringify({ users: [APP_USER] });

  consoleLog('INFO', 'Applying roles, users and removing the shipped demo accounts...');

  // base64 keeps multi-line YAML and JSON out of shell quoting entirely
  const b64 = (s) => Buffer.from(s, 'utf8').toString('base64');
  const script = [
    `set -e`,
    `echo '${b64(internalUsers)}' | base64 -d > /tmp/internal_users.yml`,
    `echo '${b64(role)}' | base64 -d > /tmp/role.json`,
    `echo '${b64(mapping)}' | base64 -d > /tmp/mapping.json`,
    `ROLE=$(cat /tmp/role.json); MAPPING=$(cat /tmp/mapping.json)`,
    `echo "role: $(${curl('PUT', `/_plugins/_security/api/roles/${APP_ROLE}`, { bodyFrom: 'ROLE' })})"`,
    `echo "mapping: $(${curl('PUT', `/_plugins/_security/api/rolesmapping/${APP_ROLE}`, { bodyFrom: 'MAPPING' })})"`,
    // securityadmin, not the API: `admin` is reserved and the API will not change it
    `plugins/opensearch-security/tools/securityadmin.sh -f /tmp/internal_users.yml -t internalusers ` +
      `-icl -nhnv -cacert ${IN_CONTAINER.ca} -cert ${IN_CONTAINER.cert} -key ${IN_CONTAINER.key} -h localhost > /tmp/sa.log 2>&1 ` +
      `|| { echo "securityadmin FAILED"; cat /tmp/sa.log; exit 1; }`,
    `echo "users: replaced"`,
    `rm -f /tmp/internal_users.yml /tmp/role.json /tmp/mapping.json /tmp/sa.log`,
  ].join('\n');

  const result = await inCluster(script);
  console.log(result);

  const survivors = await listDemoUsers();
  if (survivors.length > 0)
    throw new Error(`Demo accounts still present after configuring: ${survivors.join(', ')}`);

  return { message: `configured admin, ${DASHBOARDS_USER} and ${APP_USER}; demo accounts removed` };
}

/**
 * Which of the image's demo accounts still exist. Used as the check that
 * configureSecurity() actually took effect, and to report an unconfigured
 * cluster as the security problem it is.
 */
export async function listDemoUsers() {
  const out = await inCluster(
    `curl -s --cacert ${IN_CONTAINER.ca} --cert ${IN_CONTAINER.cert} --key ${IN_CONTAINER.key} ` +
    `"https://localhost:9200/_plugins/_security/api/internalusers" || true`
  );
  return DEMO_USERS.filter(user => new RegExp(`"${user}"\\s*:`).test(out));
}
