##### mainly for prod
hostnames:
##### full qulified domain name
  fqdn: "nbcg.me"
  frontend: "www."
  api: "api."
  keycloak: "auth."
  opensearch: "search."

##### these are external ports moastly for dev
ports:
  pgadmin: 8081
  keycloak: 8082
  opensearch-node-p1: 9200
  opensearch-node-p2: 9600
  opensearch-dashboards: 5601
  metadata-db: 15432
  redis-db: 6379
  keycloak-db: 25432
  seaweedfs-master-p1: 9333
  seaweedfs-master-p2: 19333
  seaweedfs-master-p3: 9324
  seaweedfs-volume-p1: 8083
  seaweedfs-volume-p2: 18083
  seaweedfs-volume-p3: 9325
  seaweedfs-filer-p1: 8888
  seaweedfs-filer-p2: 18888
  seaweedfs-filer-p3: 9326
  seaweedfs-s3-p1: 8333
  seaweedfs-s3-p2: 9327
  seaweedfs-webdav: 7333

zfs:
##### in prod this should be changed to the zfs path
  base: "lib-data/"

external:
  #!#!#!#!#! DO NOT ADD VALUE TO THIS VARIABLE OR SECRETS / PASSWORDS / KEYS / ... TO THE TEMPLATE FILE !#!#!#!#!#
  cobiss-token:

##### dev specific configuration to disable scurity of funcitonality
config:
  allow_account_creation: false
  enable_mfa: false