-- Task workflow v2: stages instead of statuses.
-- docs/shared/plans/task-workflow-v2.md, docs/backend/plans/task-workflow-v2.md
--
-- IN_PROGRESS and RETURNED become OPEN; a returned review task becomes the fix
-- task it really is. Writes no task_history rows (there is no system actor, by
-- design) and rewrites none: old IN_PROGRESS / RETURNED / STATUS_CHANGED values
-- stay in the log forever.
--
-- Before running in production, know the outcome in advance:
--   SELECT status, kind, count(*) FROM tasks GROUP BY 1, 2;
--
-- One transaction, so a failure leaves the v1 data untouched.
BEGIN;

-- AlterTable
ALTER TABLE "tasks" ADD COLUMN     "handoffs" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN     "lastHandoff" "TaskAction" NOT NULL DEFAULT 'CREATED';

-- A returned review task *is* a fix task in v2.
UPDATE "tasks" SET "kind" = 'FIX_METADATA' WHERE "status" = 'RETURNED' AND "kind" = 'REVIEW_PUBLISH';
UPDATE "tasks" SET "lastHandoff" = 'RETURNED' WHERE "status" = 'RETURNED';
UPDATE "tasks" SET "status" = 'OPEN' WHERE "status" IN ('IN_PROGRESS', 'RETURNED');

-- Handoff stack: [{creator, null}, {assignee, kind}], or just [{assignee, kind}]
-- when someone filed the task for themselves.
UPDATE "tasks" SET "handoffs" = CASE
  WHEN "createdByUserId" = "assignedToUserId" THEN
    jsonb_build_array(jsonb_build_object('userId', "assignedToUserId", 'kind', "kind"::text))
  ELSE
    jsonb_build_array(
      jsonb_build_object('userId', "createdByUserId", 'kind', NULL),
      jsonb_build_object('userId', "assignedToUserId", 'kind', "kind"::text)
    )
END;

-- AlterEnum (as generated by prisma migrate diff)
CREATE TYPE "TaskStatus_new" AS ENUM ('OPEN', 'COMPLETED', 'CANCELLED');
ALTER TABLE "public"."tasks" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "tasks" ALTER COLUMN "status" TYPE "TaskStatus_new" USING ("status"::text::"TaskStatus_new");
ALTER TYPE "TaskStatus" RENAME TO "TaskStatus_old";
ALTER TYPE "TaskStatus_new" RENAME TO "TaskStatus";
DROP TYPE "public"."TaskStatus_old";
ALTER TABLE "tasks" ALTER COLUMN "status" SET DEFAULT 'OPEN';

COMMIT;
