name: dev-nbcg


##### DEVELOPMENT #####
networks:
  backend:
    driver: bridge

services:
##### POSTGRES #####
  db:
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT_INTERNAL}"
    networks:
      - backend

##### REDIS #####
  redis:
    ports:
      - "${REDIS_PORT}:${REDIS_PORT_INTERNAL}"
    networks:
      - backend

##### PGADMIN #####
  pgadmin:
    ports:
      - "${PGADMIN_PORT}:${PGADMIN_PORT_INTERNAL}"
    environment:
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    networks:
      - backend

##### KEYCLOAK
  keycloak:
    command: start-dev --import-realm
    ports:
      - "${KEYCLOAK_PORT}:${KEYCLOAK_PORT_INTERNAL}"
    environment:
      KC_HOSTNAME_PORT: ${KEYCLOAK_PORT}
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_LOG_LEVEL: debug
    networks:
      - backend

  keycloak-db:
    ports:
      - "${KEYCLOAK_POSTGRES_PORT}:${KEYCLOAK_POSTGRES_PORT_INTERNAL}"
    networks:
      - backend

##### PGSYNC
  pgsync:
    networks:
      - backend

##### OPENSEARCH
  opensearch-node:
    environment:
      - DISABLE_SECURITY_PLUGIN=true
    ports:
      - "${OPENSEARCH_NODE_P1}:${OPENSEARCH_NODE_P1_INTERNAL}"
      - "${OPENSEARCH_NODE_P2}:${OPENSEARCH_NODE_P2_INTERNAL}"
    networks:
      - backend

  opensearch-dashboards:
    ports:
      - "${OPENSEARCH_DASHBOARDS}:${OPENSEARCH_DASHBOARDS_INTERNAL}"
    networks:
      - backend

##### SeaweedFS
  master:
    ports:
      - "${SEAWEEDFS_MASTER_P1}:${SEAWEEDFS_MASTER_P1_INTERNAL}"
      - "${SEAWEEDFS_MASTER_P2}:${SEAWEEDFS_MASTER_P2_INTERNAL}"
      - "${SEAWEEDFS_MASTER_P3}:${SEAWEEDFS_MASTER_P3_INTERNAL}"
    networks:
      - backend
  volume:
    ports:
      - "${SEAWEEDFS_VOLUME_P1}:${SEAWEEDFS_VOLUME_P1_INTERNAL}"
      - "${SEAWEEDFS_VOLUME_P2}:${SEAWEEDFS_VOLUME_P2_INTERNAL}"
      - "${SEAWEEDFS_VOLUME_P3}:${SEAWEEDFS_VOLUME_P3_INTERNAL}"
    networks:
      - backend