name: nbcg

volumes:
##### POSTGRES
  postgres-data:
##### PGADMIN
  pgadmin-data:
##### KEYCLOAK
  keycloak-data:
##### OPENSEARCH
  opensearch-data:
##### REDIS
  redis-data:
##### SEAWEEDFS
  seaweedfs-data:

services:
##### POSTGRESQL #####
  db:
    image: postgres:18.3
    restart: unless-stopped
    shm_size: 1024mb
    command: [ "postgres", "-c", "wal_level=logical" ]
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: "--data-checksums"
    volumes:
     - postgres-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3

##### PGADMIN #####
  pgadmin:
    image: dpage/pgadmin4:9.12.0
    volumes:
     - ./infrastructure/docker/pgadmin/servers.json:/pgadmin4/servers.json:ro
     - pgadmin-data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
      keycloak-db:
        condition: service_healthy

##### REDIS #####
  redis:
    image: redis:8.6.1
    restart: unless-stopped
    volumes:
      - redis-data:/data

##### KEYCLOAK DATABASE #####
  keycloak-db:
    image: postgres:18.3
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
      POSTGRES_USER: ${KEYCLOAK_POSTGRES_USER}
      POSTGRES_DB: ${KEYCLOAK_POSTGRES_DB}
      POSTGRES_INITDB_ARGS: "--data-checksums"
    volumes:
     - keycloak-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${KEYCLOAK_POSTGRES_USER} -d ${KEYCLOAK_POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3

##### KEYCLOAK #####
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.4
    restart: unless-stopped
    depends_on:
      keycloak-db:
        condition: service_healthy
    environment:
      KC_HOSTNAME_PORT: ${INTERNAL_HTTPHTTP}
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:${INTERNAL_POSTGRES}/${KEYCLOAK_POSTGRES_DB}
      KC_DB_USERNAME: ${KEYCLOAK_POSTGRES_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}

##### PGSYNC #####
  pgsync:
    image: toluaina1/pgsync:latest
    restart: unless-stopped
    environment:
      - REDIS_CHECKPOINT=true
      - REDIS_HOST=redis
      - PG_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
      - ELASTICSEARCH_URL=http://opensearch-node:${INTERNAL_OPENSEARCH_NODE_P1}
      - ELASTICSEARCH=false
      - OPENSEARCH=true
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started # Redis is usually instant, but you can add a healthcheck there too
      opensearch-node:
        condition: service_healthy
    volumes:
      - ./infrastructure/docker/pgsync/schema.json:/app/schema.json
    command: -c schema.json -d -b

##### OPENSEARCH #####
  opensearch-node:
    image: opensearchproject/opensearch:3.5.0
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node
      - discovery.seed_hosts=opensearch-node
      - cluster.initial_cluster_manager_nodes=opensearch-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q '\"status\":\"green\"\\|\"status\":\"yellow\"'"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data

##### dashboard
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:3.5.0
    depends_on:
     - opensearch-node
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch-node:${INTERNAL_OPENSEARCH_NODE_P1}"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: true

##### SEAWEEDFS #####
  master:
    image: chrislusf/seaweedfs:4.23 # use a remote image
    restart: unless-stopped
    ports:
      - ${EXTERNAL_SEAWEEDFS_MASTER_P1}:9333
      - ${EXTERNAL_SEAWEEDFS_MASTER_P2}:19333
      - ${EXTERNAL_SEAWEEDFS_MASTER_P3}:9324
    command: 'master -ip=master -ip.bind=0.0.0.0 -metricsPort=9324'
  volume:
    image: chrislusf/seaweedfs:4.23 # use a remote image
    volumes:
      - seaweedfs-data:/data
    restart: unless-stopped
    ports:
      - ${EXTERNAL_SEAWEEDFS_VOLUME_P1}:8080
      - ${EXTERNAL_SEAWEEDFS_VOLUME_P2}:18080
      - ${EXTERNAL_SEAWEEDFS_VOLUME_P3}:9325
    command: 'volume -ip=volume -master="master:9333" -ip.bind=0.0.0.0 -port=8080 -metricsPort=9325'
    depends_on:
      - master
  filer:
    image: chrislusf/seaweedfs:4.23 # use a remote image
    restart: unless-stopped
    ports:
      - ${EXTERNAL_SEAWEEDFS_FILER_P1}:8888
      - ${EXTERNAL_SEAWEEDFS_FILER_P2}:18888
      - ${EXTERNAL_SEAWEEDFS_FILER_P3}:9326
    command: 'filer -ip=filer -master="master:9333" -ip.bind=0.0.0.0 -metricsPort=9326'
    tty: true
    stdin_open: true
    depends_on:
      - master
      - volume
  s3:
    image: chrislusf/seaweedfs:4.23 # use a remote image
    restart: unless-stopped
    ports:
      - ${EXTERNAL_SEAWEEDFS_S3_P1}:8333
      - ${EXTERNAL_SEAWEEDFS_S3_P2}:9327
    command: 's3 -filer="filer:8888" -ip.bind=0.0.0.0 -metricsPort=9327'
    depends_on:
      - master
      - volume
      - filer
  webdav:
    image: chrislusf/seaweedfs:4.23 # use a remote image
    restart: unless-stopped
    ports:
      - ${EXTERNAL_SEAWEEDFS_WEBDAV}:7333
    command: 'webdav -filer="filer:8888"'
    depends_on:
      - master
      - volume
      - filer