export interface ResolvedCode {
  code: string;
  en:  string;
  cnr: string; // Crnogorski / Serbo-Croatian
}

// Language codes (COMARC 101) – ISO 639-2
const LANGUAGE_MAP: Record<string, [string, string]> = {
  // [English, Crnogorski]
  aar: ["Afar", "Afar"],
  abk: ["Abkhazian", "Abhaski"],
  ace: ["Achinese", "Acehneski"],
  ach: ["Acoli", "Akoli"],
  ada: ["Adangme", "Adangme"],
  ady: ["Adyghe", "Adigejski"],
  afa: ["Afro-Asiatic languages", "Afroazijski jezici"],
  afh: ["Afrihili", "Afrihili"],
  afr: ["Afrikaans", "Afrikanerski"],
  ain: ["Ainu", "Ainu"],
  aka: ["Akan", "Akan"],
  akk: ["Akkadian", "Akadski"],
  alb: ["Albanian", "Albanski"],
  sqi: ["Albanian", "Albanski"],
  ale: ["Aleut", "Aleutski"],
  alg: ["Algonquian languages", "Algonkinski jezici"],
  alt: ["Southern Altai", "Južnoaltajski"],
  amh: ["Amharic", "Amharski"],
  ang: ["Old English", "Staroengleski"],
  anp: ["Angika", "Angika"],
  apa: ["Apache languages", "Apaški jezici"],
  ara: ["Arabic", "Arapski"],
  arc: ["Aramaic", "Aramejski"],
  arg: ["Aragonese", "Aragonski"],
  arm: ["Armenian", "Jermenski"],
  hye: ["Armenian", "Jermenski"],
  arn: ["Mapuche", "Mapuče"],
  arp: ["Arapaho", "Arapaho"],
  art: ["Artificial languages", "Vještački jezici"],
  arw: ["Arawak", "Aravak"],
  asm: ["Assamese", "Asamski"],
  ast: ["Asturian", "Asturijski"],
  ath: ["Athapascan languages", "Atapaski jezici"],
  aus: ["Australian languages", "Australski jezici"],
  ava: ["Avaric", "Avarski"],
  ave: ["Avestan", "Avestanski"],
  awa: ["Awadhi", "Avadhi"],
  aym: ["Aymara", "Ajmara"],
  aze: ["Azerbaijani", "Azerbejdžanski"],
  bak: ["Bashkir", "Baškirski"],
  bam: ["Bambara", "Bambara"],
  ban: ["Balinese", "Balijski"],
  baq: ["Basque", "Baskijski"],
  eus: ["Basque", "Baskijski"],
  bas: ["Basa", "Basa"],
  bat: ["Baltic languages", "Baltički jezici"],
  bel: ["Belarusian", "Bjeloruski"],
  bem: ["Bemba", "Bemba"],
  ben: ["Bengali", "Bengalski"],
  ber: ["Berber languages", "Berberski jezici"],
  bho: ["Bhojpuri", "Bhojpuri"],
  bih: ["Bihari languages", "Biharski jezici"],
  bik: ["Bikol", "Bikol"],
  bin: ["Bini", "Bini"],
  bis: ["Bislama", "Bislama"],
  bla: ["Blackfoot", "Blekfutski"],
  bnt: ["Bantu languages", "Bantu jezici"],
  bos: ["Bosnian", "Bosanski"],
  bra: ["Braj", "Braj"],
  bre: ["Breton", "Bretonski"],
  btk: ["Batak languages", "Batak jezici"],
  bua: ["Buriat", "Burjatski"],
  bug: ["Buginese", "Buginski"],
  bul: ["Bulgarian", "Bugarski"],
  bur: ["Burmese", "Burmanski"],
  cad: ["Caddo", "Kaddo"],
  cai: ["Central American Indian languages", "Indijanski jezici Srednje Amerike"],
  cat: ["Catalan", "Katalonski"],
  cau: ["Caucasian languages", "Kavkaski jezici"],
  ceb: ["Cebuano", "Cebuano"],
  cel: ["Celtic languages", "Keltski jezici"],
  cha: ["Chamorro", "Čamoro"],
  chb: ["Chibcha", "Čibča"],
  che: ["Chechen", "Čečenski"],
  chg: ["Chagatai", "Čagatajski"],
  chi: ["Chinese", "Kineski"],
  zho: ["Chinese", "Kineski"],
  chk: ["Chuukese", "Čuukski"],
  chm: ["Mari", "Marijski"],
  chn: ["Chinook jargon", "Činuk žargon"],
  cho: ["Choctaw", "Čoktav"],
  chp: ["Chipewyan", "Čipevjan"],
  chr: ["Cherokee", "Čeroki"],
  chu: ["Church Slavic", "Crkvenoslovenski"],
  chv: ["Chuvash", "Čuvaški"],
  chy: ["Cheyenne", "Šajen"],
  cnr: ["Montenegrin", "Crnogorski"],
  cop: ["Coptic", "Koptski"],
  cor: ["Cornish", "Kornvolski"],
  cos: ["Corsican", "Korzikanski"],
  cpe: ["Creoles and pidgins, English based", "Kreolski i pidžin jezici na engleskoj osnovi"],
  cpf: ["Creoles and pidgins, French-based", "Kreolski i pidžin jezici na francuskoj osnovi"],
  cpp: ["Creoles and pidgins, Portuguese-based", "Kreolski i pidžin jezici na portugalskoj osnovi"],
  cre: ["Cree", "Kri"],
  crh: ["Crimean Tatar", "Krimskotalarski"],
  crp: ["Creoles and pidgins", "Kreolski i pidžin jezici"],
  csb: ["Kashubian", "Kašupski"],
  cus: ["Cushitic languages", "Kuštički jezici"],
  cze: ["Czech", "Češki"],
  ces: ["Czech", "Češki"],
  dan: ["Danish", "Danski"],
  dar: ["Dargwa", "Dargvanski"],
  day: ["Dayak languages", "Dajački jezici"],
  del: ["Delaware", "Delaverski"],
  den: ["Slave", "Dejne-žie"],
  deu: ["German", "Nemački"],
  ger: ["German", "Nemački"],
  dgr: ["Dogrib", "Dogrib"],
  din: ["Dinka", "Dinka"],
  div: ["Divehi", "Divehi"],
  doi: ["Dogri", "Dogri"],
  dra: ["Dravidian languages", "Dravidski jezici"],
  dsb: ["Lower Sorbian", "Donjolužičkosrpski"],
  dua: ["Duala", "Duala"],
  dum: ["Middle Dutch", "Srednji nizozemski"],
  dut: ["Dutch", "Nizozemski"],
  nld: ["Dutch", "Nizozemski"],
  dyu: ["Dyula", "Djula"],
  dzo: ["Dzongkha", "Džongka"],
  efi: ["Efik", "Efik"],
  egy: ["Egyptian", "Staroegipatski"],
  eka: ["Ekajuk", "Ekajuk"],
  ell: ["Greek, Modern", "Novogrčki"],
  gre: ["Greek, Modern", "Novogrčki"],
  elx: ["Elamite", "Elamski"],
  eng: ["English", "Engleski"],
  enm: ["Middle English", "Srednji engleski"],
  epo: ["Esperanto", "Esperanto"],
  est: ["Estonian", "Estonski"],
  ewe: ["Ewe", "Eve"],
  ewo: ["Ewondo", "Evondo"],
  fan: ["Fang", "Fang"],
  fao: ["Faroese", "Farski"],
  fas: ["Persian", "Perzijski"],
  per: ["Persian", "Perzijski"],
  fat: ["Fanti", "Fanti"],
  fij: ["Fijian", "Fidžijski"],
  fil: ["Filipino", "Filipinski"],
  fin: ["Finnish", "Finski"],
  fon: ["Fon", "Fon"],
  fra: ["French", "Francuski"],
  fre: ["French", "Francuski"],
  frm: ["Middle French", "Srednji francuski"],
  fro: ["Old French", "Starofrancuski"],
  fry: ["Frisian", "Frizijski"],
  ful: ["Fulah", "Fula"],
  fur: ["Friulian", "Furljanski"],
  gaa: ["Ga", "Ga"],
  gay: ["Gayo", "Gajo"],
  gba: ["Gbaya", "Gbaja"],
  gem: ["Germanic languages", "Germanski jezici"],
  geo: ["Georgian", "Gruzijski"],
  kat: ["Georgian", "Gruzijski"],
  gla: ["Scottish Gaelic", "Škotski gelski"],
  gle: ["Irish", "Irski"],
  glg: ["Galician", "Galicijski"],
  glv: ["Manx", "Manks"],
  gmh: ["Middle High German", "Srednji visokonjemački"],
  goh: ["Old High German", "Starovisokonjemački"],
  gon: ["Gondi", "Gondi"],
  gor: ["Gorontalo", "Gorontalo"],
  got: ["Gothic", "Gotski"],
  grb: ["Grebo", "Grebo"],
  grc: ["Ancient Greek", "Starogrčki"],
  guj: ["Gujarati", "Gudžaratski"],
  gwi: ["Gwich'in", "Gvičin"],
  hai: ["Haida", "Haida"],
  hat: ["Haitian", "Haitski kreolski"],
  hau: ["Hausa", "Hausa"],
  haw: ["Hawaiian", "Havajski"],
  heb: ["Hebrew", "Hebrejski"],
  her: ["Herero", "Herero"],
  hil: ["Hiligaynon", "Hiligajnon"],
  him: ["Western Pahari", "Zapadni pahari"],
  hin: ["Hindi", "Hindi"],
  hit: ["Hittite", "Hetitski"],
  hmn: ["Hmong", "Hmong"],
  hrv: ["Croatian", "Hrvatski"],
  hun: ["Hungarian", "Mađarski"],
  hup: ["Hupa", "Hupa"],
  iba: ["Iban", "Iban"],
  ibo: ["Igbo", "Igbo"],
  ice: ["Icelandic", "Islandski"],
  isl: ["Icelandic", "Islandski"],
  ido: ["Ido", "Ido"],
  iii: ["Sichuan Yi", "Sečuanski Ji"],
  iku: ["Inuktitut", "Inuktitut"],
  ile: ["Interlingue", "Interlingve"],
  ilo: ["Iloko", "Iloko"],
  ina: ["Interlingua", "Interlingva"],
  inc: ["Indic languages", "Indijski jezici"],
  ind: ["Indonesian", "Indonežanski"],
  ine: ["Indo-European languages", "Indoevropski jezici"],
  ipk: ["Inupiaq", "Inupjak"],
  ira: ["Iranian languages", "Iranski jezici"],
  iro: ["Iroquoian languages", "Irokeški jezici"],
  ita: ["Italian", "Italijanski"],
  jav: ["Javanese", "Javanski"],
  jpn: ["Japanese", "Japanski"],
  jpr: ["Judeo-Persian", "Judeo-perzijski"],
  jrb: ["Judeo-Arabic", "Judeo-arapski"],
  kaa: ["Kara-Kalpak", "Karakalpački"],
  kab: ["Kabyle", "Kabilski"],
  kac: ["Kachin", "Kačinski"],
  kal: ["Kalaallisut", "Grenlandski"],
  kam: ["Kamba", "Kamba"],
  kan: ["Kannada", "Kanarezijski"],
  kas: ["Kashmiri", "Kašmirski"],
  kau: ["Kanuri", "Kanuri"],
  kaz: ["Kazakh", "Kazaški"],
  khm: ["Khmer", "Kmerski"],
  khi: ["Khoisan languages", "Koisanski jezici"],
  kik: ["Kikuyu", "Kikuju"],
  kin: ["Kinyarwanda", "Kinjaruanda"],
  kir: ["Kyrgyz", "Kirgiski"],
  kmb: ["Kimbundu", "Kimbundu"],
  kok: ["Konkani", "Konkani"],
  kom: ["Komi", "Komi"],
  kon: ["Kongo", "Kongo"],
  kor: ["Korean", "Korejski"],
  kos: ["Kosraean", "Kosrejski"],
  kur: ["Kurdish", "Kurdski"],
  lao: ["Lao", "Laoški"],
  lat: ["Latin", "Latinski"],
  lav: ["Latvian", "Letonski"],
  lim: ["Limburgish", "Limburški"],
  lin: ["Lingala", "Lingala"],
  lit: ["Lithuanian", "Litvanski"],
  ltz: ["Luxembourgish", "Luksemburški"],
  lub: ["Luba-Katanga", "Luba-katanga"],
  lug: ["Ganda", "Ganda"],
  luo: ["Luo", "Luo"],
  lus: ["Mizo", "Mizo"],
  mac: ["Macedonian", "Makedonski"],
  mkd: ["Macedonian", "Makedonski"],
  mad: ["Madurese", "Madurski"],
  mag: ["Magahi", "Magahi"],
  mah: ["Marshallese", "Maršalski"],
  mai: ["Maithili", "Majtili"],
  mal: ["Malayalam", "Malajalamski"],
  man: ["Mandingo", "Mandingo"],
  mao: ["Maori", "Maorski"],
  mri: ["Maori", "Maorski"],
  mar: ["Marathi", "Marathski"],
  mas: ["Masai", "Masajski"],
  may: ["Malay", "Malajski"],
  msa: ["Malay", "Malajski"],
  mdf: ["Moksha", "Mokšanski"],
  mdr: ["Mandar", "Mandar"],
  men: ["Mende", "Mende"],
  mga: ["Middle Irish", "Srednji irski"],
  mic: ["Mi'kmaq", "Mikmak"],
  min: ["Minangkabau", "Minangkabau"],
  mis: ["Uncoded languages", "Nekodifikovani jezici"],
  mkh: ["Mon-Khmer languages", "Mon-kmerski jezici"],
  mlg: ["Malagasy", "Malgaški"],
  mlt: ["Maltese", "Malteški"],
  mnc: ["Manchu", "Mandžurski"],
  mni: ["Manipuri", "Manipurski"],
  mno: ["Manobo languages", "Manobo jezici"],
  moh: ["Mohawk", "Mohočki"],
  mon: ["Mongolian", "Mongolski"],
  mos: ["Mossi", "Mosi"],
  mul: ["Multiple languages", "Više jezika"],
  mun: ["Munda languages", "Mundski jezici"],
  mus: ["Creek", "Krik"],
  mya: ["Burmese", "Burmanski"],
  nah: ["Nahuatl", "Navatl"],
  nai: ["North American Indian languages", "Sjevernoindijaski jezici"],
  nap: ["Neapolitan", "Napuljski"],
  nau: ["Nauru", "Nauruanski"],
  nav: ["Navajo", "Navaho"],
  nbl: ["South Ndebele", "Južni ndebele"],
  nde: ["North Ndebele", "Sjeverni ndebele"],
  ndo: ["Ndonga", "Ndonga"],
  nds: ["Low German", "Donjonjemački"],
  nep: ["Nepali", "Nepalski"],
  new: ["Nepal Bhasa", "Nevari"],
  nia: ["Nias", "Nias"],
  nic: ["Niger-Kordofanian languages", "Niger-kordofanski jezici"],
  niu: ["Niuean", "Niuejski"],
  nno: ["Norwegian Nynorsk", "Norveški (nynorsk)"],
  nob: ["Norwegian Bokmål", "Norveški (bokmål)"],
  nog: ["Nogai", "Nogajski"],
  non: ["Old Norse", "Staronordijski"],
  nor: ["Norwegian", "Norveški"],
  nqo: ["N'Ko", "N'Ko"],
  nso: ["Northern Sotho", "Sjeverni soto"],
  nub: ["Nubian languages", "Nubijski jezici"],
  nya: ["Chichewa", "Čičeva"],
  nym: ["Nyamwezi", "Njamvezi"],
  nyn: ["Nyankole", "Njankole"],
  nyo: ["Nyoro", "Njoro"],
  nzi: ["Nzima", "Nzima"],
  oci: ["Occitan", "Oksitanski"],
  ojw: ["Ojibwa", "Odžibve"],
  ori: ["Odia", "Odija"],
  orm: ["Oromo", "Oromo"],
  oss: ["Ossetian", "Osetinski"],
  ota: ["Ottoman Turkish", "Osmanski turski"],
  oto: ["Otomian languages", "Otomijski jezici"],
  paa: ["Papuan languages", "Papuanski jezici"],
  pag: ["Pangasinan", "Pangasinski"],
  pal: ["Pahlavi", "Pahlavski"],
  pam: ["Pampanga", "Pampanga"],
  pan: ["Punjabi", "Pandžabski"],
  pap: ["Papiamento", "Papiamento"],
  pau: ["Palauan", "Palauski"],
  peo: ["Old Persian", "Staroperzijski"],
  phi: ["Philippine languages", "Filipinski jezici"],
  pli: ["Pali", "Palijski"],
  pol: ["Polish", "Poljski"],
  pon: ["Pohnpeian", "Ponpejski"],
  por: ["Portuguese", "Portugalski"],
  pra: ["Prakrit languages", "Prakrit jezici"],
  pro: ["Old Provençal", "Staroprovansalski"],
  pus: ["Pashto", "Paštunski"],
  que: ["Quechua", "Kečuanski"],
  raj: ["Rajasthani", "Radžastanski"],
  rap: ["Rapanui", "Rapanui"],
  rar: ["Rarotongan", "Rarotonški"],
  roa: ["Romance languages", "Romanski jezici"],
  roh: ["Romansh", "Romanš"],
  rom: ["Romany", "Romski"],
  ron: ["Romanian", "Rumunski"],
  rum: ["Romanian", "Rumunski"],
  run: ["Rundi", "Rundi"],
  rus: ["Russian", "Ruski"],
  sad: ["Sandawe", "Sandave"],
  sag: ["Sango", "Sango"],
  sah: ["Yakut", "Jakutski"],
  sai: ["South American Indian languages", "Južnoindijaski jezici"],
  sal: ["Salishan languages", "Saliski jezici"],
  sam: ["Samaritan Aramaic", "Samarijanski aramejski"],
  san: ["Sanskrit", "Sanskritski"],
  sas: ["Sasak", "Sasak"],
  sat: ["Santali", "Santali"],
  scn: ["Sicilian", "Sicilijanski"],
  sco: ["Scots", "Škotski"],
  sel: ["Selkup", "Selkupski"],
  sem: ["Semitic languages", "Semitski jezici"],
  sga: ["Old Irish", "Staroirski"],
  sgn: ["Sign languages", "Znakovni jezici"],
  shn: ["Shan", "Šan"],
  sid: ["Sidamo", "Sidamo"],
  sin: ["Sinhala", "Sinhaleški"],
  sio: ["Siouan languages", "Sijuanski jezici"],
  sit: ["Sino-Tibetan languages", "Sinotibet jezici"],
  sla: ["Slavic languages", "Slavenski jezici"],
  slk: ["Slovak", "Slovački"],
  slo: ["Slovak", "Slovački"],
  slv: ["Slovenian", "Slovenački"],
  sma: ["Southern Sami", "Južni sami"],
  sme: ["Northern Sami", "Sjeverni sami"],
  smi: ["Sami languages", "Sami jezici"],
  smj: ["Lule Sami", "Lule sami"],
  smn: ["Inari Sami", "Inari sami"],
  smo: ["Samoan", "Samoanski"],
  sms: ["Skolt Sami", "Skolt sami"],
  sna: ["Shona", "Šona"],
  snd: ["Sindhi", "Sindski"],
  snk: ["Soninke", "Soninke"],
  sog: ["Sogdian", "Sogdijski"],
  som: ["Somali", "Somalski"],
  son: ["Songhai languages", "Songaj jezici"],
  sot: ["Southern Sotho", "Južni soto"],
  spa: ["Spanish", "Španski"],
  srd: ["Sardinian", "Sardinijski"],
  srn: ["Sranan Tongo", "Sranan tongo"],
  srp: ["Serbian", "Srpski"],
  srr: ["Serer", "Serer"],
  ssa: ["Nilo-Saharan languages", "Nilosaharski jezici"],
  ssw: ["Swati", "Svati"],
  suk: ["Sukuma", "Sukuma"],
  sun: ["Sundanese", "Sundanski"],
  sus: ["Susu", "Susu"],
  sux: ["Sumerian", "Sumerski"],
  swa: ["Swahili", "Svahili"],
  swe: ["Swedish", "Švedski"],
  syc: ["Classical Syriac", "Klasični sirijski"],
  syr: ["Syriac", "Sirijski"],
  tah: ["Tahitian", "Tahićanski"],
  tai: ["Tai languages", "Tai jezici"],
  tam: ["Tamil", "Tamilski"],
  tat: ["Tatar", "Tatarski"],
  tel: ["Telugu", "Telugu"],
  tem: ["Timne", "Timne"],
  ter: ["Tereno", "Tereno"],
  tet: ["Tetum", "Tetum"],
  tgk: ["Tajik", "Tadžički"],
  tgl: ["Tagalog", "Tagalog"],
  tha: ["Thai", "Tajlandski"],
  tib: ["Tibetan", "Tibetanski"],
  bod: ["Tibetan", "Tibetanski"],
  tig: ["Tigre", "Tigre"],
  tir: ["Tigrinya", "Tigrinja"],
  tiv: ["Tiv", "Tiv"],
  tkl: ["Tokelau", "Tokelauski"],
  tlh: ["Klingon", "Klingonski"],
  tli: ["Tlingit", "Tlingit"],
  tmh: ["Tamashek", "Tamašek"],
  tog: ["Tonga", "Tonga"],
  ton: ["Tonga (Tonga Islands)", "Tonga (Tongansko ostrvo)"],
  tpi: ["Tok Pisin", "Tok pisin"],
  tsi: ["Tsimshian", "Cimšianski"],
  tsn: ["Tswana", "Cvana"],
  tso: ["Tsonga", "Conga"],
  tuk: ["Turkmen", "Turkmenski"],
  tum: ["Tumbuka", "Tumbuka"],
  tur: ["Turkish", "Turski"],
  tut: ["Altaic languages", "Altajski jezici"],
  tvl: ["Tuvalu", "Tuvaluanski"],
  twi: ["Twi", "Tvi"],
  tyv: ["Tuvinian", "Tuvinski"],
  udm: ["Udmurt", "Udmurtski"],
  uga: ["Ugaritic", "Ugaritski"],
  uig: ["Uyghur", "Ujgurski"],
  ukr: ["Ukrainian", "Ukrajinski"],
  umb: ["Umbundu", "Umbundu"],
  und: ["Undetermined", "Neodređeno"],
  urd: ["Urdu", "Urdu"],
  uzb: ["Uzbek", "Uzbekistanski"],
  vai: ["Vai", "Vai"],
  ven: ["Venda", "Venda"],
  vie: ["Vietnamese", "Vijetnamski"],
  vol: ["Volapük", "Volapik"],
  vot: ["Votic", "Votski"],
  wak: ["Wakashan languages", "Vakašanski jezici"],
  wal: ["Walamo", "Valamo"],
  war: ["Waray", "Varaj"],
  was: ["Washo", "Vašo"],
  wel: ["Welsh", "Velški"],
  cym: ["Welsh", "Velški"],
  wen: ["Sorbian languages", "Lužičkosrpski jezici"],
  wln: ["Walloon", "Valonski"],
  wol: ["Wolof", "Volof"],
  xal: ["Kalmyk", "Kalmički"],
  xho: ["Xhosa", "Kosa"],
  yao: ["Yao", "Jao"],
  yap: ["Yapese", "Japski"],
  yid: ["Yiddish", "Jidiš"],
  yor: ["Yoruba", "Joruba"],
  ypk: ["Yupik languages", "Jupički jezici"],
  zap: ["Zapotec", "Zapotečki"],
  zen: ["Zenaga", "Zenaga"],
  zha: ["Zhuang", "Džuang"],
  znd: ["Zande languages", "Zande jezici"],
  zul: ["Zulu", "Zulu"],
  zun: ["Zuni", "Zuni"],
};

// COMARC 102 – country codes
const COUNTRY_MAP: Record<string, [string, string]> = {
  // [English, Crnogorski]
  svn: ["Slovenia", "Slovenija"],
  hrv: ["Croatia", "Hrvatska"],
  srb: ["Serbia", "Srbija"],
  bih: ["Bosnia and Herzegovina", "Bosna i Hercegovina"],
  mne: ["Montenegro", "Crna Gora"],
  mkd: ["North Macedonia", "Sjeverna Makedonija"],
  deu: ["Germany", "Njemačka"],
  aut: ["Austria", "Austrija"],
  ita: ["Italy", "Italija"],
  fra: ["France", "Francuska"],
  esp: ["Spain", "Španija"],
  prt: ["Portugal", "Portugalija"],
  gbr: ["United Kingdom", "Ujedinjeno Kraljevstvo"],
  usa: ["United States", "Sjedinjene Američke Države"],
  can: ["Canada", "Kanada"],
  rus: ["Russia", "Rusija"],
  chn: ["China", "Kina"],
  jpn: ["Japan", "Japan"],
  kor: ["South Korea", "Južna Koreja"],
  ind: ["India", "Indija"],
  aus: ["Australia", "Australija"],
  bra: ["Brazil", "Brazil"],
  mex: ["Mexico", "Meksiko"],
  arg: ["Argentina", "Argentina"],
  zaf: ["South Africa", "Južna Afrika"],
  egy: ["Egypt", "Egipat"],
  tur: ["Turkey", "Turska"],
  int: ["International organization", "Međunarodna organizacija"],
};

// 001/b – Record type
const RECORD_TYPE_MAP: Record<string, [string, string]> = {
  a: ["Textual material, printed",          "Tekstualna građa, štampana"],
  b: ["Textual material, manuscript",        "Tekstualna građa, rukopis"],
  c: ["Music, printed",                      "Muzikalije, štampane"],
  d: ["Music, manuscript",                   "Muzikalije, rukopis"],
  e: ["Cartographic material, printed",      "Kartografska građa, štampana"],
  f: ["Cartographic material, manuscript",   "Kartografska građa, rukopis"],
  g: ["Projected/video material",            "Građa za video projekc., videosnimci i filmovi"],
  i: ["Non-musical sound recording",         "Zvučni snimci, nemuzički"],
  j: ["Musical sound recording",             "Zvučni snimci, muzički"],
  k: ["Two-dimensional graphic",             "Dvodimenzionalna grafika"],
  l: ["Electronic resource",                 "Elektronski izvori"],
  m: ["Multimedia",                          "Multimedijska građa"],
  r: ["Three-dimensional object",            "Trodimenzionalni proizvodi i predmeti"],
  u: ["Event",                               "Događaj"],
};

// 001/c – Bibliographic level
const BIBLIOGRAPHIC_LEVEL_MAP: Record<string, [string, string]> = {
  a: ["Analytic (component part)",  "Analitički nivo (sastavni dio)"],
  c: ["Collection",                 "Zbirni zapis"],
  d: ["Performed work (event)",     "Izvedeno djelo"],
  i: ["Integrating resource",       "Integrativni izvor"],
  m: ["Monograph",                  "Monografska publikacija"],
  s: ["Serial",                     "Serijska publikacija"],
};

// 001/b + 001/c combined → human material type label
// Key format: "<b_code><c_code>"  e.g. "am" = printed text monograph = book
const MATERIAL_TYPE_MAP: Record<string, [string, string]> = {
  am: ["Book",                          "Knjiga"],
  as: ["Journal / Serial",              "Časopis / Serijska publikacija"],
  aa: ["Article",                       "Članak"],
  ai: ["Integrating text resource",     "Integrativni tekstualni izvor"],
  cm: ["Printed music",                 "Štampana muzikalija"],
  cs: ["Music serial",                  "Muzička serijska publikacija"],
  dm: ["Music manuscript",              "Muzikalija u rukopisu"],
  em: ["Printed map",                   "Štampana karta"],
  es: ["Map serial",                    "Kartografska serijska publikacija"],
  fm: ["Manuscript map",                "Karta u rukopisu"],
  gm: ["Video / Film",                  "Video / Film"],
  gs: ["Video serial",                  "Video serijska publikacija"],
  im: ["Non-musical sound recording",   "Nemuzikal. zvučni snimak"],
  is: ["Non-musical sound serial",      "Nemuzikal. zvučna serijska publ."],
  jm: ["Musical sound recording",       "Muzički zvučni snimak"],
  js: ["Musical sound serial",          "Muzička zvučna serijska publ."],
  km: ["Graphic",                       "Grafika"],
  lm: ["Electronic resource",           "Elektronski izvor"],
  ls: ["Electronic serial",             "Elektronski serijski izvor"],
  li: ["Website / Database",            "Web lokacija / Baza podataka"],
  mm: ["Multimedia",                    "Multimedija"],
  rm: ["Three-dimensional object",      "Trodimenzionalni predmet"],
  ud: ["Performed work",                "Izvedeno djelo"],
  ac: ["Collection (analytic)",         "Zbirka (analitička)"],
  mc: ["Collection (monographic)",      "Zbirka (monografska)"],
};

// 105/a – Illustration codes
const ILLUSTRATION_CODE_MAP: Record<string, [string, string]> = {
  a: ["Illustrations",          "Ilustracije"],
  b: ["Maps",                   "Geografske karte"],
  c: ["Portraits",              "Portreti"],
  d: ["Charts",                 "Navigacijske karte"],
  e: ["Plans",                  "Nacrti"],
  f: ["Plates",                 "Prilozi (povezani)"],
  g: ["Music",                  "Note"],
  h: ["Facsimiles",             "Faksimili"],
  i: ["Coats of arms",          "Grbovi"],
  j: ["Genealogical tables",    "Rodoslovne tablice"],
  k: ["Forms",                  "Obrasci"],
  l: ["Samples",                "Uzorci"],
  m: ["Sound recordings",       "Zvučni snimci"],
  n: ["Slides / Transparencies","Slajdovi, folije"],
  o: ["Illuminations",          "Iluminacije"],
  y: ["Not illustrated",        "Publikacija nije ilustrovana"],
};

// 105/b – Content type codes
const CONTENT_TYPE_MAP: Record<string, [string, string]> = {
  "8":    ["Offprint",                      "Separat"],
  "9":    ["Other",                         "Drugo"],
  a:      ["Bibliography",                  "Bibliografija"],
  b:      ["Catalogue",                     "Katalog"],
  c:      ["Index / Register",              "Registar, indeks"],
  d:      ["Abstract / Summary",            "Apstrakt, sažetak"],
  e:      ["Dictionary",                    "Rečnik"],
  f:      ["Encyclopaedia / Lexicon",       "Enciklopedija, leksikon"],
  g:      ["Directory",                     "Imenik"],
  h:      ["Yearbook",                      "Godišnjak"],
  i:      ["Statistics",                    "Statistički pregled"],
  j:      ["Textbook",                      "Udžbenik"],
  j1:     ["Primary school textbook",       "Udžbenik za osnovne škole"],
  j1d:    ["Primary school workbook",       "Radna sveska za osnovne škole"],
  j2:     ["Secondary school textbook",     "Udžbenik za srednje škole"],
  j2d:    ["Secondary school workbook",     "Radna sveska za srednje škole"],
  j3:     ["Higher education textbook",     "Udžbenik za više i visoke škole"],
  j3d:    ["Higher education workbook",     "Radna sveska za više i visoke škole"],
  jd:     ["Workbook",                      "Radna sveska"],
  k:      ["Patent",                        "Patent"],
  l:      ["Standard",                      "Standard"],
  m:      ["Doctoral dissertation",         "Doktorska disertacija"],
  m2:     ["Master's thesis",               "Magistarski rad"],
  m3:     ["Specialist thesis",             "Specijalistički rad"],
  m4:     ["Habilitation",                  "Habilitacija"],
  m5:     ["Graduate thesis",               "Diplomski rad"],
  m6:     ["Higher college graduate thesis","Diplomski rad na višoj školi"],
  m7:     ["Matura paper",                  "Maturski rad"],
  mb11:   ["Bachelor thesis (Bologna 1)",   "Diplomski rad (1. stepen bolonjskih studija)"],
  mb12:   ["Final paper (Bologna 1)",       "Završni rad (1. stepen bolonjskih studija)"],
  mb13:   ["Diploma project (Bologna 1)",   "Diplomski projekt (1. stepen bolonjskih studija)"],
  mb14:   ["Diploma seminar (Bologna 1)",   "Diplomski seminar (1. stepen bolonjskih studija)"],
  mb15:   ["Dramaturgical work (Bologna 1)","Dramaturški rad (1. stepen bolonjskih studija)"],
  mb16:   ["Study reflection (Bologna 1)",  "Rad završne refleksije (1. stepen bolonjskih studija)"],
  mb21:   ["Master thesis (Bologna 2)",     "Diplomski rad (2. stepen bolonjskih studija)"],
  mb22:   ["Master's thesis (Bologna)",     "Magistarski rad (bolonjske studije)"],
  mb31:   ["Doctoral dissertation (Bologna)","Doktorska disertacija (bolonjske studije)"],
  n:      ["Laws",                          "Zakoni"],
  o:      ["Numerical table",               "Numerička tabela"],
  o1:     ["Tariffs",                       "Tarife"],
  o2:     ["Price list",                    "Cenovnik"],
  p:      ["Technical report",              "Tehnički izveštaj"],
  p1:     ["Primary school paper",          "Seminarski rad u osnovnoj školi"],
  p2:     ["Secondary school paper",        "Seminarski rad u srednjoj školi"],
  p3:     ["Primary school research",       "Istraživački rad u osnovnoj školi"],
  p4:     ["Secondary school research",     "Istraživački rad u srednjoj školi"],
  p5:     ["Higher education research",     "Istraživački rad na višoj ili visokoj školi"],
  q:      ["Examination material",          "Ispitna građa (testovi)"],
  r:      ["Fundamental research",          "Temeljno istraživanje"],
  r1:     ["Review article",                "Pregledni rad"],
  r2:     ["Scientific paper",              "Naučni rad"],
  r3:     ["Preliminary communication",     "Prethodno saopštenje"],
  r4:     ["Professional paper",            "Stručni rad"],
  r5:     ["Conference report",             "Izveštaj sa konferencije"],
  r6:     ["Uncategorised paper",           "Rad nije kategorisan"],
  r7:     ["Research data",                 "Istraživački podaci"],
  s:      ["International treaty",          "Međunarodni ugovor"],
  t:      ["Applied research",              "Razvojno istraživanje"],
  u:      ["Rulebook",                      "Pravilnik"],
  u1:     ["Statute",                       "Statut"],
  u2:     ["Corporate programme",           "Program korporacije"],
  v:      ["Handbook",                      "Priručnik"],
  v1:     ["Guide",                         "Vodič"],
  v2:     ["Instructions",                  "Uputstva"],
  w:      ["Application research",          "Aplikativno istraživanje"],
  x1:     ["Comics",                        "Strip"],
  x2:     ["Picture book",                  "Slikovnica"],
  y:      ["Literary review",               "Književni prikaz/pregled"],
  z:      ["Proceedings",                   "Zbornik"],
};

// 105/f – Literary form
const LITERARY_FORM_MAP: Record<string, [string, string]> = {
  a:   ["Novel",                              "Roman"],
  a1:  ["Social novel",                       "Socijalni roman"],
  a2:  ["Adventure novel",                    "Avanturistički roman"],
  a3:  ["Historical / war novel",             "Istorijski, ratni roman"],
  a4:  ["Crime / spy / detective novel",      "Kriminalistički, špijunski, detektivski roman"],
  a5:  ["(Auto)biographical novel",           "(Auto)biografski roman"],
  a6:  ["Science fiction",                    "(Naučno)fantastična proza"],
  b:   ["Drama",                              "Drama"],
  b1:  ["Radio drama",                        "Radio-drama"],
  b2:  ["Screenplay",                         "Scenario"],
  b3:  ["Libretto",                           "Libreto"],
  c:   ["Essay",                              "Esej"],
  d:   ["Humour / Satire / Parody",           "Humor, satira, parodija"],
  e:   ["Letters",                            "Pisma"],
  f:   ["Short prose",                        "Kratka proza"],
  f1:  ["Fairy tales",                        "Bajke"],
  f2:  ["Anecdotes",                          "Anegdote"],
  f3:  ["Aphorisms / Proverbs",               "Aforizmi, poslovice"],
  f4:  ["Fables",                             "Basne"],
  g:   ["Poetry",                             "Poezija"],
  g1:  ["Riddles",                            "Zagonetke"],
  g2:  ["Poetry anthology",                   "Pesnička antologija"],
  h:   ["Speech",                             "Govor"],
  h2:  ["Interview",                          "Intervju"],
  i:   ["Memoirs / Diaries / Travel writing", "Memoari, dnevnici, reportaže, putopisi"],
  i1:  ["Memoirs / Diary",                    "Memoari, dnevnik"],
  i2:  ["Travel writing / Reportage",         "Putopis, reportaža"],
  x:   ["Folk literature",                    "Narodna književnost"],
  x1:  ["Folk poetry",                        "Narodno pesništvo"],
  x2:  ["Folk prose",                         "Narodna proza"],
  x3:  ["Myths / Legends",                    "Mitovi, legende"],
  z:   ["Other / Mixed literary forms",       "Drugi i mješoviti književni oblici"],
  z1:  ["Anthology",                          "Antologija"],
  z2:  ["Collected works",                    "Sabrana djela"],
  z3:  ["Selected works",                     "Izabrana djela"],
};

// 105/g – Biography code
const BIOGRAPHY_CODE_MAP: Record<string, [string, string]> = {
  a: ["Autobiography",           "Autobiografija"],
  b: ["Individual biography",    "Individualna biografija"],
  c: ["Collective biography",    "Kolektivna biografija"],
  d: ["Contains biographical data", "Sadrži biografske podatke"],
  y: ["Not a biographical work", "Nije biografsko djelo"],
};

// HERE IF WE ARE GOING TO NEED IT
// 105/f - example from LITERARY_FORM_MAP i2 goes to i here
const LITERARY_FORM_DISPLAY_MAP: Record<string, [string, string]> = {
  a: ["Novel",               "Roman"],
  b: ["Drama",               "Drama"],
  c: ["Essay",               "Esej"],
  d: ["Humour / Satire",     "Humor, satira"],
  e: ["Letters",             "Pisma"],
  f: ["Short prose",         "Kratka proza"],
  g: ["Poetry",              "Poezija"],
  h: ["Speech",              "Govor"],
  i: ["Documentary lit.",    "Dokumentar.lit."],
  x: ["Folk literature",     "Narodna književnost"],
  z: ["Other literary forms","Drugi književni oblici"],
};

// Relator codes (700/4, 701/4, 702/4, 710/4, 711/4, 712/4) – Appendix H
const RELATOR_CODE_MAP: Record<string, [string, string]> = {
  "005": ["Actor",                        "Glumac"],
  "010": ["Adapter",                      "Prerađivač"],
  "018": ["Animator",                     "Animator"],
  "020": ["Annotator",                    "Pisac anotacija"],
  "030": ["Arranger",                     "Aranžer"],
  "040": ["Artist",                       "Umetnik"],
  "050": ["Assignee",                     "Korisnik prava"],
  "060": ["Associated name",              "Ime povezano s jedinicom"],
  "070": ["Author",                       "Autor"],
  "080": ["Author of additional text",    "Autor dodatnog teksta"],
  "090": ["Author of screenplay",         "Autor scenarija"],
  "100": ["Bibliographic antecedent",     "Bibliografski prethodnik"],
  "110": ["Bookbinder",                   "Knjigovezac"],
  "120": ["Book jacket designer",         "Dizajner poveza"],
  "130": ["Book designer",                "Dizajner knjige"],
  "140": ["Cover designer",               "Dizajner omota"],
  "150": ["Bookplate designer",           "Autor ekslibrisa"],
  "160": ["Bookseller",                   "Knjižar"],
  "170": ["Calligrapher",                 "Kaligraf"],
  "180": ["Cartographer",                 "Kartograf"],
  "190": ["Censor",                       "Cenzor"],
  "200": ["Choreographer",                "Koreograf"],
  "206": ["Collector of folk material",   "Sakupljač narodne građe"],
  "210": ["Commentator",                  "Komentator"],
  "220": ["Compiler",                     "Priređivač, sakupljač"],
  "230": ["Composer",                     "Kompozitor"],
  "240": ["Type-setter",                  "Slovoslagač"],
  "245": ["Conceptor",                    "Autor ideje"],
  "250": ["Conductor",                    "Dirigent"],
  "260": ["Copyright holder",             "Vlasnik autorskih prava"],
  "270": ["Corrector of manuscripts",     "Korektor rukopisa"],
  "273": ["Curator of exhibition",        "Kustos izložbe"],
  "275": ["Dancer",                       "Igrač (plesač)"],
  "280": ["Dedicatee",                    "Osoba/ustanova kojoj je knjiga posvećena"],
  "290": ["Dedicator",                    "Autor posvete"],
  "300": ["Director",                     "Režiser"],
  "305": ["Thesis advisor",               "Autor teze"],
  "310": ["Distributor",                  "Distributer"],
  "320": ["Donor",                        "Donator"],
  "330": ["Dubious author",               "Sumnjivi autor"],
  "340": ["Editor",                       "Urednik"],
  "341": ["Editorial board member",       "Član uredničkog odbora"],
  "342": ["Guest editor",                 "Gostujući urednik"],
  "343": ["Editor of area",               "Urednik za određeno područje"],
  "344": ["Editor in chief",              "Glavni urednik"],
  "345": ["Managing editor",              "Odgovorni urednik"],
  "346": ["Editor in chief and managing editor", "Glavni i odgovorni urednik"],
  "347": ["Editorial advisory board member", "Član uredničkog savjeta"],
  "348": ["Chair of editorial board",     "Predsjednik uredničkog savjeta"],
  "349": ["Technical editor",             "Tehnički urednik"],
  "350": ["Engraver",                     "Graver"],
  "360": ["Etcher",                       "Bakropisac"],
  "370": ["Film editor",                  "Filmski montažer"],
  "380": ["Forger",                       "Falsifikator"],
  "390": ["Former owner",                 "Prethodni vlasnik"],
  "400": ["Funder",                       "Finansijer/sponzor"],
  "410": ["Graphic technician",           "Grafički tehničar"],
  "420": ["Honoree",                      "Osoba kojoj je knjiga poklonjena"],
  "430": ["Illuminator",                  "Iluminator"],
  "440": ["Illustrator",                  "Ilustrator"],
  "445": ["Music producer",               "Muzički producent"],
  "450": ["Inscriber",                    "Pisac izjave o poklonu"],
  "460": ["Interviewee",                  "Intervjuisana osoba"],
  "470": ["Interviewer",                  "Osoba koja intervjuiše"],
  "480": ["Librettist",                   "Pisac libreta"],
  "490": ["Licensee",                     "Osoba koja ima dozvolu za štampanje"],
  "500": ["Licensor",                     "Potpisnik dozvole za štampanje"],
  "510": ["Lithographer",                 "Litograf"],
  "520": ["Lyricist",                     "Pisac teksta za kompoziciju"],
  "530": ["Metal engraver",               "Graver u metalu"],
  "540": ["Monitor",                      "Nadzornik/ugovarač"],
  "545": ["Musician",                     "Muzičar"],
  "550": ["Narrator",                     "Narator"],
  "557": ["Organizer of meeting",         "Organizator sastanka"],
  "560": ["Originator",                   "Začetnik/osnivač"],
  "570": ["Other",                        "Drugo"],
  "580": ["Papermaker",                   "Proizvođač papira"],
  "590": ["Performer",                    "Izvođač"],
  "600": ["Photographer",                 "Fotograf"],
  "605": ["Host",                         "Voditelj emisije"],
  "610": ["Printer",                      "Štampar"],
  "620": ["Printer of plates",            "Štampar ploča"],
  "630": ["Producer",                     "Producent"],
  "632": ["Production designer",          "Dizajner prizora"],
  "635": ["Programmer",                   "Programer"],
  "637": ["Project manager",              "Vođa projekta"],
  "640": ["Proofreader",                  "Korektor"],
  "650": ["Publisher",                    "Izdavač"],
  "660": ["Recipient",                    "Primalac"],
  "670": ["Recording engineer",           "Tehnički urednik snimanja"],
  "675": ["Reviewer",                     "Ocjenjivač"],
  "680": ["Rubricator",                   "Rubrikator"],
  "690": ["Screenwriter",                 "Scenarist"],
  "700": ["Scribe",                       "Pisar"],
  "710": ["Secretary",                    "Sekretar"],
  "720": ["Signer",                       "Potpisnik"],
  "721": ["Singer",                       "Pevač"],
  "730": ["Translator",                   "Prevodilac"],
  "740": ["Type designer",                "Dizajner slova"],
  "750": ["Typographer",                  "Tipograf/slovolagač"],
  "760": ["Wood engraver",                "Rezbar"],
  "770": ["Writer of accompanying material", "Pisac propratne građe"],
  "901": ["Reviewer",                     "Recenzent"],
  "903": ["Translation editor",           "Redaktor prevoda"],
  "913": ["Abstract author",              "Autor sažetka"],
  "914": ["Abstract translator",          "Prevodilac sažetka"],
  "919": ["Art editor",                   "Likovni urednik"],
  "925": ["Consultant",                   "Konsultant"],
  "926": ["Language editor",              "Lektor"],
  "927": ["Research collaborator",        "Saradnik na istraživanju"],
  "928": ["Corresponding author",         "Kontakt autor"],
  "929": ["Legacy holder",                "Nosilac legata"],
  "991": ["Mentor",                       "Mentor"],
  "992": ["Committee member",             "Član komisije"],
  "993": ["Defence committee member",     "Član komisije za odbranu"],
  "994": ["Co-mentor",                    "Komentor"],
};

// ---------------------------------------------------------------------------
// Resolvers
// ---------------------------------------------------------------------------

/**
 * Resolve an ISO 639-2/B language code to a ResolvedCode object.
 * Falls back gracefully: unknown codes return the raw code as both names.
 */
export function resolveLanguage(code: string): ResolvedCode {
  const key = code.toLowerCase();
  const entry = LANGUAGE_MAP[key];
  return {
    code: key,
    en:  entry?.[0] ?? code.toUpperCase(),
    cnr: entry?.[1] ?? code.toUpperCase(),
  };
}

/**
 * Resolve a UNIMARC country code to a ResolvedCode object.
 * Falls back gracefully: unknown codes return the raw code as both names.
 */
export function resolveCountry(code: string): ResolvedCode {
  const key = code.toLowerCase();
  const entry = COUNTRY_MAP[key];
  return {
    code: key,
    en:  entry?.[0] ?? code.toUpperCase(),
    cnr: entry?.[1] ?? code.toUpperCase(),
  };
}

export function resolveRecordType(code: string): ResolvedCode {
  const key = code.toLowerCase();
  const entry = RECORD_TYPE_MAP[key];
  return { code: key, en: entry?.[0] ?? code.toUpperCase(), cnr: entry?.[1] ?? code.toUpperCase() };
}

export function resolveBibliographicLevel(code: string): ResolvedCode {
  const key = code.toLowerCase();
  const entry = BIBLIOGRAPHIC_LEVEL_MAP[key];
  return { code: key, en: entry?.[0] ?? code.toUpperCase(), cnr: entry?.[1] ?? code.toUpperCase() };
}

export function resolveMaterialType(recordTypeCode: string, bibLevelCode: string): ResolvedCode {
  const key = `${recordTypeCode.toLowerCase()}${bibLevelCode.toLowerCase()}`;
  const entry = MATERIAL_TYPE_MAP[key];
  return { code: key, en: entry?.[0] ?? key.toUpperCase(), cnr: entry?.[1] ?? key.toUpperCase() };

  /* IF WE ARE GOING TO NEED IT
  if (literaryFormCode) {
    const parentKey = literaryFormCode[0].toLowerCase();
    const display = LITERARY_FORM_DISPLAY_MAP[parentKey];
    if (display) return {
        code: `${recordTypeCode}${bibLevelCode}:${literaryFormCode}`,
        en:  display[0],
        cnr: display[1],
    };
    }
  */
}

export function resolveIllustrationCode(code: string): ResolvedCode {
  const key = code.toLowerCase();
  const entry = ILLUSTRATION_CODE_MAP[key];
  return { code: key, en: entry?.[0] ?? code, cnr: entry?.[1] ?? code };
}

export function resolveContentType(code: string): ResolvedCode {
  const entry = CONTENT_TYPE_MAP[code.toLowerCase()] ?? CONTENT_TYPE_MAP[code];
  return { code, en: entry?.[0] ?? code, cnr: entry?.[1] ?? code };
}

export function resolveLiteraryForm(code: string): ResolvedCode {
  const key = code.toLowerCase();
  const entry = LITERARY_FORM_MAP[key];
  return { code: key, en: entry?.[0] ?? code, cnr: entry?.[1] ?? code };
}

export function resolveBiographyCode(code: string): ResolvedCode {
  const key = code.toLowerCase();
  const entry = BIOGRAPHY_CODE_MAP[key];
  return { code: key, en: entry?.[0] ?? code, cnr: entry?.[1] ?? code };
}

export function resolveRelatorCode(code: string): ResolvedCode {
  const entry = RELATOR_CODE_MAP[code];
  return { code, en: entry?.[0] ?? code, cnr: entry?.[1] ?? code };
}